/* Shared PC/mobile input normalization and data-driven cooking interactions. */
class CookingInputAdapter{
  constructor(canvas,emit){this.canvas=canvas;this.emit=emit;this.pointerId=null;this.keyHeld=false;this.down=e=>{if(this.pointerId!==null)return;e.preventDefault();this.pointerId=e.pointerId;canvas.setPointerCapture(e.pointerId);this.emit({type:'pressStart',source:'pointer',point:this.point(e),time:e.timeStamp})};this.move=e=>{if(e.pointerId!==this.pointerId)return;const samples=e.getCoalescedEvents?.();for(const sample of samples?.length?samples:[e])this.emit({type:'move',source:'pointer',point:this.point(sample),time:sample.timeStamp})};this.up=e=>{if(e.pointerId!==this.pointerId)return;this.emit({type:e.type==='pointercancel'?'cancel':'pressEnd',source:'pointer',point:this.point(e),time:e.timeStamp});this.pointerId=null;try{canvas.releasePointerCapture(e.pointerId)}catch{}};canvas.addEventListener('pointerdown',this.down);canvas.addEventListener('pointermove',this.move);canvas.addEventListener('pointerup',this.up);canvas.addEventListener('pointercancel',this.up)}
  point(e){const r=this.canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*1280/r.width,y:(e.clientY-r.top)*720/r.height}}
  keyboard(down){if(down===this.keyHeld)return;this.keyHeld=down;this.emit({type:down?'pressStart':'pressEnd',source:'keyboard',point:null,time:performance.now()})}
  dispose(){this.canvas.removeEventListener('pointerdown',this.down);this.canvas.removeEventListener('pointermove',this.move);this.canvas.removeEventListener('pointerup',this.up);this.canvas.removeEventListener('pointercancel',this.up);this.keyHeld=false;this.pointerId=null}
}

const COOKING_INTERACTIONS={
  TIMING:{press(s){s.onTap?.()}},
  VIDEO_TAP_SEQUENCE:{press(s){s.options.onVideoTap?.()}},
  VIDEO_RHYTHM:{press(s){s.options.onVideoTap?.()}},
  VIDEO_SEASONING:{press(s){s.options.onSeasoningHit?.()}},
  VIDEO_STIR_TIMING:{press(s){s.options.onSeasoningHit?.()}},
  VIDEO_PASTA_TIMING:{press(s){s.options.onSeasoningHit?.()}},
  VIDEO_PASTA_ACTION:{press(s){s.options.onVideoTap?.()}},
  VIDEO_RAMEN:{press(s,e){s.options.onRamenInput?.('press',e)},release(s,e){s.options.onRamenInput?.('release',e)}},
  VIDEO_PASTA_HOLD:{press(s,e){s.heldSources.add(e.source);s.options.onHoldChange?.(true)},release(s,e){s.heldSources.delete(e.source);const held=s.heldSources.size>0;s.options.onHoldChange?.(held);if(!held)s.options.onHoldEnd?.()}},
  VIDEO_HOLD:{press(s,e){s.heldSources.add(e.source);s.options.onHoldChange?.(s.heldSources.size>0)},release(s,e){s.heldSources.delete(e.source);const held=s.heldSources.size>0;s.options.onHoldChange?.(held);if(!held)s.options.onHoldEnd?.()}},
  HOLD_AMOUNT:{press(s,e){s.heldSources.add(e.source)},release(s,e){s.heldSources.delete(e.source);if(!s.heldSources.size)s.finishAmount()}},
  STIR:{press(s,e){if(!e.point)return;s.dragging=true;s.lastAngle=s.angleAt(e.point);s.setTool(e.point);if(s.step.stirLaps){s.stirSweep=0;s.stirDirection=0}},move(s,e){if(!s.dragging||!e.point)return;const a=s.angleAt(e.point);if(s.lastAngle!==null){let d=a-s.lastAngle;if(d>Math.PI)d-=Math.PI*2;if(d< -Math.PI)d+=Math.PI*2;s.turn+=Math.abs(d);if(s.step.stirLaps){const center=s.step.stirCenter||{x:640,y:426},radius=Math.hypot(e.point.x-center.x,e.point.y-center.y),min=s.step.stirRadiusMin||74,max=s.step.stirRadiusMax||300;if(radius<min||radius>max){s.stirSweep=0;s.stirDirection=0}else if(Math.abs(d)>.012){const direction=Math.sign(d);if(!s.stirDirection)s.stirDirection=direction;if(direction===s.stirDirection)s.stirSweep+=Math.abs(d);else{s.stirSweep=Math.max(0,s.stirSweep-Math.abs(d));if(s.stirSweep<.12)s.stirDirection=direction}if(s.stirSweep>=Math.PI*2)s.registerStirLap()}}else if(s.turn>=s.step.targetTurns*Math.PI*2)s.complete(true)}s.lastAngle=a;s.setTool(e.point)},release(s){s.dragging=false;s.lastAngle=null;if(s.step.stirLaps){if(s.stirSweep>=(s.step.stirMinSweep||Math.PI*1.5))s.registerStirLap();s.stirSweep=0;s.stirDirection=0}}},
  COOK_TIMING:{press(s){s.onTap?.()}},
  FLIP:{press(s){if(s.flipElapsed===null)s.flipElapsed=0}},
  POINTER_DRAW:{press(s,e){if(!e.point)return;s.drawing=true;s.lastPoint=e.point;s.currentStroke=[e.point]},move(s,e){if(!s.drawing||!e.point)return;s.strokeLength+=Math.hypot(e.point.x-s.lastPoint.x,e.point.y-s.lastPoint.y);s.currentStroke.push(e.point);s.lastPoint=e.point},release(s){if(!s.drawing)return;s.drawing=false;if(s.currentStroke?.length>1)s.strokes.push(s.currentStroke);s.currentStroke=null;if(s.strokeLength>=s.step.minLength)s.complete(s.strokes);else s.options.onFeedback?.(`시럽을 조금 더 길게 그려주세요. ${Math.round(s.strokeLength)}/${s.step.minLength}`)}}
};

class CookingInteractionSystem{
  constructor(canvas,step,sharedState,options={}){
    this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false});this.step=step;this.state=sharedState||{};this.options=options;this.onTap=options.onTap||null;this.heldSources=new Set();this.phaseIndex=0;this.amount=0;this.turn=0;this.lastAngle=null;this.dragging=false;this.stirSweep=0;this.stirDirection=0;this.stirLapsCompleted=0;this.strokes=this.state[step.stateKey]||[];this.strokeLength=0;this.currentStroke=null;this.drawing=false;this.flipElapsed=null;this.flipTurn=0;this.eggCrackElapsed=null;this.cookElapsed=0;this.done=false;this.overflow=false;this.message='';this.time=0;this.toolPoint={x:640,y:403};this.toolAngle=-Math.PI/2;this.toolSpeed=0;this.lastToolPoint=null;
    this.interaction=COOKING_INTERACTIONS[step.interaction];if(!this.interaction)throw Error(`Unknown cooking interaction: ${step.interaction}`);
    this.input=new CookingInputAdapter(canvas,event=>this.inputEvent(event));
    this.assets={background:new Image(),pan:new Image(),ingredient:new Image(),pouring:new Image(),leftHand:new Image(),rightHand:new Image()};
    this.assets.background.src='assets/frying-prototype/kitchen-background.png';this.assets.pan.src='assets/frying-prototype/empty-red-pan.png';this.assets.ingredient.src=step.asset||'assets/frying-prototype/food/pancake-core.png';this.assets.pouring.src='assets/frying-prototype/pouring-hand-bowl.png';this.assets.leftHand.src='assets/frying-prototype/left-hand.png';this.assets.rightHand.src='assets/frying-prototype/right-hand.png';
  }
  dispose(){this.input.dispose();this.heldSources.clear()}
  keyboard(down){this.input.keyboard(down)}
  setHeldSource(source,down){this.inputEvent({type:down?'pressStart':'pressEnd',source,point:null,time:performance.now()})}
  inputEvent(event){if(this.done)return;const method=event.type==='pressStart'?'press':event.type==='move'?'move':event.type==='cancel'?'cancel':'release';this.interaction[method]?.(this,event)}
  get phase(){return this.step.phases?.[this.phaseIndex]||this.step}
  get ingredient(){return this.phase.ingredient||this.step.ingredient}
  get amountKey(){return this.phase.stateKey||this.step.stateKey}
  get scene(){return this.step.scene==='bowl'?'bowl':'pan'}
  angleAt(p){const center=this.step.stirCenter||{x:640,y:426};return Math.atan2(p.y-center.y,p.x-center.x)}
  registerStirLap(){if(this.done||!this.step.stirLaps||this.stirLapsCompleted>=this.step.stirLaps)return;this.stirSweep=this.stirSweep>=Math.PI*2?this.stirSweep-Math.PI*2:0;this.stirLapsCompleted++;this.options.onStirLap?.(this.stirLapsCompleted,this.step.stirLaps,this.stirDirection);if(this.stirLapsCompleted>=this.step.stirLaps){if(this.step.stirPlayback==='on-lap')this.options.onStirPlaybackComplete?.();else this.complete(true)}}
  setTool(p){if(this.lastToolPoint){const dx=p.x-this.lastToolPoint.x,dy=p.y-this.lastToolPoint.y,d=Math.hypot(dx,dy);this.toolSpeed=Math.min(1,d/32);if(d>1)this.toolAngle=Math.atan2(dy,dx)+Math.PI/2}this.toolPoint={x:p.x,y:p.y};this.lastToolPoint={x:p.x,y:p.y}}
  cookPhase(){const p=this.step;if(this.cookElapsed<p.rawDuration)return'raw';if(this.cookElapsed<(p.edgeEnd||p.perfectStart*.57))return'edge';if(this.cookElapsed<(p.bubbleStart||p.perfectStart*.82))return'bubbles';if(this.cookElapsed<p.perfectStart)return'nearly';if(this.cookElapsed<p.burnStart)return'perfect';return'burnt'}
  tryCookTiming(){if(this.step.interaction!=='COOK_TIMING'||this.cookPhase()!=='perfect')return false;this.complete(true);return true}
  acceptTimedHit(){if(this.done)return false;if(this.step.interaction==='COOK_TIMING'){if(this.cookPhase()==='perfect')return this.tryCookTiming();if(this.cookPhase()==='burnt'){this.state[this.step.stateKey]='burnt';this.complete('burnt');return true}return false}if(this.step.animation==='egg-crack'){if(this.eggCrackElapsed!==null)return false;this.eggCrackElapsed=0;return true}this.complete(this.step.output??true);return true}
  finishAmount(){const phase=this.phase;if(phase.overflowAt&&this.amount>=phase.overflowAt){this.overflow=true;this.message='반죽이 팬 밖으로 넘쳤어요. 다시 부어보세요.';this.amount=0;this.state[phase.stateKey]=0;this.options.onFeedback?.(this.message);return}if(this.amount<phase.minAmount){this.message=`${phase.label||'목표량'}까지 조금 더 눌러주세요.`;this.options.onFeedback?.(this.message);return}if(this.amount>phase.maxAmount){this.message='조금 많이 나왔어요. 양을 맞춰 다시 시도해요.';this.amount=0;this.state[phase.stateKey]=0;this.options.onFeedback?.(this.message);return}this.state[phase.stateKey]=this.amount;this.message=`${phase.label||''} 적정량!`;this.options.onFeedback?.(this.message);if(this.step.phases&&this.phaseIndex<this.step.phases.length-1){this.phaseIndex++;this.amount=0;this.overflow=false;this.message=`이제 ${this.phase.label}을 넣어요.`;this.options.onFeedback?.(this.message);return}this.complete(this.amount)}
  complete(value){if(this.done)return;this.done=true;if(this.step.interaction==='FLIP')this.state[this.step.stateKey]=true;else if(this.step.interaction==='POINTER_DRAW')this.state[this.step.stateKey]=this.strokes;else if(this.step.stateKey)this.state[this.step.stateKey]=value;this.options.onComplete?.(value)}
  update(dt){this.time+=dt;if(this.step.interaction==='HOLD_AMOUNT'&&this.heldSources.size){this.amount=Math.min(1.25,this.amount+this.phase.rate*dt);this.state[this.amountKey]=this.amount;this.overflow=!!(this.phase.overflowAt&&this.amount>=this.phase.overflowAt)}if(this.step.interaction==='VIDEO_PASTA_HOLD'&&this.heldSources.size&&!this.done){this.amount=Math.min(1,this.amount+(this.step.rate||.22)*dt);this.state.pastaSauceAmount=this.amount}if(this.step.interaction==='COOK_TIMING'&&(!this.step.video||this.step.manualTrigger)){this.cookElapsed+=dt;if(this.step.manualTrigger&&this.step.burnStart&&this.cookElapsed>=this.step.burnStart)this.cookElapsed=this.step.rawDuration||0}if(this.eggCrackElapsed!==null&&!this.done){this.eggCrackElapsed+=dt;if(this.eggCrackElapsed>=.92)this.complete(true)}if(this.flipElapsed!==null&&!this.done){this.flipElapsed+=dt;if(this.flipElapsed>=this.step.duration)this.complete(true)}}
  render(){const c=this.ctx;c.clearRect(0,0,1280,720);this.drawBackground(c);if(this.scene==='bowl')this.drawBowl(c);else this.drawPan(c);if(this.step.interaction==='HOLD_AMOUNT')this.drawAmountMeter(c);if(this.step.interaction==='COOK_TIMING')this.drawCookMeter(c);if(this.step.interaction==='POINTER_DRAW')this.drawSyrup(c)}
  drawBackground(c){const img=this.assets.background;if(img.complete&&img.naturalWidth)c.drawImage(img,0,0,1280,720);else{const g=c.createLinearGradient(0,0,0,720);g.addColorStop(0,'#f8e8c8');g.addColorStop(1,'#dfb27c');c.fillStyle=g;c.fillRect(0,0,1280,720)}}
  drawBowl(c){
    c.save();c.shadowColor='#563d3060';c.shadowBlur=24;c.shadowOffsetY=20;c.fillStyle='#bda17d';c.beginPath();c.ellipse(640,470,270,110,0,0,Math.PI*2);c.fill();c.restore();const rim=c.createLinearGradient(0,345,0,525);rim.addColorStop(0,'#fffdf2');rim.addColorStop(.55,'#f4e6cb');rim.addColorStop(1,'#bd9772');c.fillStyle=rim;c.beginPath();c.ellipse(640,431,267,112,0,0,Math.PI*2);c.fill();c.fillStyle='#aa7751';c.beginPath();c.ellipse(640,420,222,77,0,0,Math.PI*2);c.fill();c.fillStyle='#f1dfbc';c.beginPath();c.ellipse(640,412,216,70,0,0,Math.PI*2);c.fill();
    c.save();c.beginPath();c.ellipse(640,412,207,63,0,0,Math.PI*2);c.clip();if(this.state.eggAdded||this.eggCrackElapsed!==null)this.ellipse(c,640,410,42,20,'#fff2ce');if(this.state.eggAdded)this.ellipse(c,641,404,22,20,'#ffc83e');this.drawPowders(c);
    const mixed=this.state.batterMixed||this.step.interaction==='STIR';if(mixed){const swirl=this.turn+this.time*2.2;const g=c.createRadialGradient(637,410,5,640,412,170);g.addColorStop(0,'#f5e3bb');g.addColorStop(.65,'#e8c98d');g.addColorStop(1,'#c99759');this.ellipse(c,640,412,183,51,g);c.save();c.translate(640,412);c.rotate(swirl*.12);for(let i=0;i<7;i++){c.strokeStyle=i%2?'#fff0ca99':'#b9854f70';c.lineWidth=3+(i%3);c.beginPath();c.ellipse(Math.sin(swirl+i)*23,Math.cos(swirl+i)*7,38+i*17,8+i*5,.04,0,Math.PI*1.5);c.stroke()}c.restore();if(this.step.interaction==='STIR'){for(let i=0;i<3;i++){const a=swirl*.7+i*2.1;this.ellipse(c,640+Math.cos(a)*100,412+Math.sin(a)*26,5,3,'#fff4d088')}}}c.restore();c.strokeStyle='#fffdf4';c.lineWidth=11;c.beginPath();c.ellipse(640,431,267,112,0,0,Math.PI*2);c.stroke();
    if(this.step.interaction==='TIMING'){this.drawHand(c,'left',420,330,.20,-.36);this.drawHand(c,'right',855,336,.20,.52);if(this.eggCrackElapsed===null)this.drawEgg(c,640,325);else this.drawCrackedEgg(c)}else if(this.step.interaction==='HOLD_AMOUNT'){this.drawHandBowl(c)}else if(this.step.interaction==='STIR'){this.drawHand(c,'left',430,414,.18,.1);this.drawWhisk(c)}this.text(c,'재료 볼',640,568,20,'#fff8e8')
  }
  drawPowders(c){for(const [key,color] of [['powderAmount','#d9bb84'],['sugarAmount','#fff9e9']]){const n=Math.floor((this.state[key]||0)*40);for(let i=0;i<n;i++){const a=i*2.399,r=Math.sqrt((i+.4)/Math.max(40,n));this.ellipse(c,640+Math.cos(a)*r*142,412+Math.sin(a)*r*40,2.5+(i%3),2+(i%2),color)}}}
  drawEgg(c,x,y){this.ellipse(c,x,y+5,39,49,'#d8b98b');this.ellipse(c,x,y,37,47,'#fff5df');this.ellipse(c,x+3,y+8,16,17,'#ffce53');this.ellipse(c,x-10,y-18,10,17,'#fffdf5')}
  drawCrackedEgg(c){const t=Math.min(1,this.eggCrackElapsed/.9),lift=Math.sin(Math.min(1,t*1.2)*Math.PI)*16,fall=Math.max(0,(t-.23)/.77);c.save();c.translate(640,320-lift);c.rotate(-.42*t);c.fillStyle='#fff3d4';c.beginPath();c.moveTo(-30,16);c.quadraticCurveTo(-45,-24,-15,-39);c.lineTo(-4,-21);c.lineTo(8,-38);c.quadraticCurveTo(37,-14,26,18);c.closePath();c.fill();c.restore();c.save();c.translate(640+3*Math.sin(t*4),340+fall*62);this.ellipse(c,0,0,20+fall*6,12+fall*8,'#fff9e8');this.ellipse(c,0,1,12+fall*3,12+fall*2,'#ffc842');c.restore();if(t>.35){for(const sign of [-1,1]){c.save();c.translate(640+sign*(18+(t-.35)*75),324+(t-.35)*45);c.rotate(sign*t*1.8);c.fillStyle='#fff4dc';c.beginPath();c.moveTo(0,0);c.lineTo(sign*27,-15);c.lineTo(sign*15,16);c.closePath();c.fill();c.strokeStyle='#dfc89f';c.lineWidth=3;c.stroke();c.restore()}}}
  drawHand(c,side,x,y,scale,angle=0){const img=side==='left'?this.assets.leftHand:this.assets.rightHand;if(!img.complete||!img.naturalWidth)return;c.save();c.translate(x,y);c.rotate(angle);const w=img.naturalWidth*scale,h=img.naturalHeight*scale;c.drawImage(img,-w/2,-h/2,w,h);c.restore()}
  drawHandBowl(c){const img=this.assets.pouring;if(!img.complete||!img.naturalWidth){this.drawHand(c,'right',848,285,.19,.48);return}const sugar=this.ingredient==='sugar',tilt=this.heldSources.size?-.18-.12*Math.sin(this.time*9):-.04;c.save();c.translate(sugar?837:820,250);c.rotate(tilt);c.drawImage(img,-img.naturalWidth*.115,-img.naturalHeight*.115,img.naturalWidth*.23,img.naturalHeight*.23);c.restore();if(this.heldSources.size)this.drawIngredientStream(c)}
  drawIngredientStream(c){const type=this.ingredient;if(type==='batter'){const stream=c.createLinearGradient(918,268,666,425);stream.addColorStop(0,'#f8e8c8');stream.addColorStop(.55,'#f1ddb6');stream.addColorStop(1,'#e5c996');c.save();c.globalAlpha=.92;c.strokeStyle=stream;c.lineWidth=22;c.lineCap='round';c.beginPath();c.moveTo(920,270);c.bezierCurveTo(850,315,785,356,667,421);c.stroke();c.globalAlpha=.58;c.strokeStyle='#fff3db';c.lineWidth=6;c.beginPath();c.moveTo(913,270);c.bezierCurveTo(846,311,782,353,669,417);c.stroke();for(let i=0;i<5;i++){const p=(this.time*1.8+i/5)%1;this.ellipse(c,920-245*p,270+150*p,2.5,2.5,'#fff3dd')}c.restore();return}const color=type==='sugar'?'#fff9e9':'#e5d0a6';for(let i=0;i<18;i++){const p=(this.time*1.3+i/18)%1,x=790-140*p+Math.sin(i*7+this.time*10)*13,y=294+117*p;c.globalAlpha=.7;c.save();c.translate(x,y);c.rotate(i*2.1);c.fillStyle=color;c.fillRect(-2,-2,4,4);c.restore()}c.globalAlpha=1}
  drawWhisk(c){const p=this.toolPoint,angle=this.toolAngle;c.save();c.translate(p.x,p.y);c.rotate(angle);c.shadowColor='#392b1e66';c.shadowBlur=7;c.fillStyle='#ad7641';c.beginPath();c.roundRect(-8,-161,16,126,8);c.fill();c.strokeStyle='#9e9c91';c.lineWidth=4;c.lineCap='round';for(let i=-3;i<=3;i++){c.beginPath();c.moveTo(i*4,-34);c.quadraticCurveTo(i*6,4,i*2,23);c.stroke()}c.restore()}
  drawPan(c){
    const step=this.step,panImg=this.assets.pan,flip=step.interaction==='FLIP'&&this.flipElapsed!==null?this.flipElapsed:null;let panX=0,panY=0,panRot=0,panScaleY=1;
    if(flip!==null){
      const t=Math.min(1,flip/step.duration),anticipate=this.easeInOut(Math.min(1,t/.10)),flick=this.easeOut(Math.max(0,Math.min(1,(t-.10)/.10))),recover=this.easeOut(Math.max(0,Math.min(1,(t-.20)/.30))),catchPan=this.easeOut(Math.max(0,Math.min(1,(t-.78)/.12))),settle=this.easeOut(Math.max(0,Math.min(1,(t-.90)/.10)));
      if(t<.10){panX=-13*anticipate;panY=11*anticipate;panRot=-.018*anticipate}
      else if(t<.20){panX=-13+44*flick;panY=11-36*flick;panRot=-.018+.065*flick;panScaleY=1-.035*flick}
      else {const recovery=1-recover;panX=31*recovery*(1-catchPan)-4*Math.sin(Math.PI*settle)*(1-t);panY=-25*recovery*(1-catchPan)+7*Math.sin(Math.PI*settle);panRot=.047*recovery*(1-catchPan)-.012*Math.sin(Math.PI*settle);panScaleY=1-.035*recovery*(1-catchPan)+.018*Math.sin(Math.PI*settle)}
    }
    c.save();c.translate(640+panX,430+panY);c.rotate(panRot);c.scale(1,panScaleY);if(panImg.complete&&panImg.naturalWidth)c.drawImage(panImg,-465,-270,970,546);else this.ellipse(c,0,0,280,128,'#38383c');c.restore();this.drawHand(c,'right',1030+panX,510+panY,.17,panRot+.24);this.drawHand(c,'left',425+panX,477+panY,.15,panRot-.25);
    if(step.interaction==='HOLD_AMOUNT'&&step.ingredient==='batter')this.drawPouringBatter(c);else if(['COOK_TIMING','FLIP','POINTER_DRAW'].includes(step.interaction)||this.state.batterAmount)this.drawPancake(c,flip);if(step.interaction==='HOLD_AMOUNT'&&step.ingredient==='batter'&&this.heldSources.size)this.drawIngredientStream(c);if(flip!==null){const t=flip/step.duration;if(t<.20){c.save();c.globalAlpha=.42*(1-t/.20);c.strokeStyle='#fff5df';c.lineWidth=6;c.beginPath();c.ellipse(640,415,198,72,0,0,Math.PI*2);c.stroke();c.restore()}const word=t<.10?'준비!':t<.20?'휙!':t<.82?'붕!':'탁!';this.text(c,word,640,t<.82?284:326,25,'#fff8e8')}
    this.text(c,'팬',640,568,20,'#fff8e8')
  }
  drawPouringBatter(c){const amount=this.amount,rx=105+Math.min(1,amount)*150,ry=34+Math.min(1,amount)*49;const g=c.createRadialGradient(610,400,5,640,414,rx);g.addColorStop(0,this.overflow?'#e3bb92':'#f8e9c9');g.addColorStop(.82,this.overflow?'#d4ad83':'#efd7ab');g.addColorStop(1,'#c28e59');c.save();c.shadowColor='#241c1750';c.shadowBlur=12;c.shadowOffsetY=8;this.ellipse(c,640,414,rx,ry,g);c.restore();c.strokeStyle='#fff3d5';c.lineWidth=5;c.beginPath();c.ellipse(640,414,rx,ry,0,0,Math.PI*2);c.stroke();if(this.heldSources.size)this.drawIngredientStream(c);if(this.overflow){this.ellipse(c,914,465,27,45,'#efdab8');this.ellipse(c,951,474,19,34,'#e6c99f')}if(this.heldSources.size){const img=this.assets.pouring;if(img.complete&&img.naturalWidth){c.save();c.translate(969,221);c.rotate(.06+.28*Math.min(1,amount/.42));c.drawImage(img,-83,-66,166,132);c.restore()}}}
  drawPancake(c,flip){const phase=this.step.interaction==='COOK_TIMING'?this.cookPhase():'perfect';let x=640,y=414,rot=0,sx=1,sy=1,airborne=false,bounce=0,shadowScale=1,shadowAlpha=.18;if(flip!==null){const t=Math.min(1,flip/this.step.duration),release=.20,land=.82;let v;
      if(t<.10){const a=this.easeInOut(t/.10);x=640-8*a;y=414+4*a;sx=1-.035*a;sy=1-.11*a}
      else if(t<release){const a=this.easeInOut((t-.10)/.10);x=632+8*a;y=418-31*a;sx=1+.035*Math.sin(Math.PI*a);sy=.89+.12*Math.sin(Math.PI*a)}
      else if(t<land){airborne=true;v=(t-release)/(land-release);const arc=4*v*(1-v);x=640+19*Math.sin(Math.PI*v);y=387-272*arc+27*v;const turn=this.easeOut(Math.min(1,v/.48));rot=Math.PI*turn;sx=1-.10*Math.sin(Math.PI*v);sy=1+.045*Math.sin(Math.PI*v);shadowScale=.58+.42*(1-arc);shadowAlpha=.07+.15*(1-arc)}
      else if(t<.91){const a=(t-land)/(.91-land),wave=Math.sin(Math.PI*a);bounce=1-a;sx=1+.10*wave;sy=1-.17*wave;y=414-10*wave;rot=Math.PI}
      else {const a=this.easeOut((t-.91)/.09);sx=1+.025*(1-a);sy=1-.035*(1-a);rot=Math.PI}
    }
    if(flip!==null)this.flipTurn=rot;
    if(airborne){c.save();c.globalAlpha=shadowAlpha;c.fillStyle='#34291f';c.beginPath();c.ellipse(640,424,110*shadowScale,27*shadowScale,0,0,Math.PI*2);c.fill();c.restore()}c.save();c.translate(x,y);const backFace=flip!==null&&((airborne&&rot>Math.PI/2)||flip/this.step.duration>=.82);c.scale(sx,sy*(backFace ? .24+.76*Math.abs(Math.cos(rot)) : 1));const img=this.assets.ingredient,batter=['raw','edge','bubbles','nearly'].includes(phase)&&this.step.interaction==='COOK_TIMING'&&this.step.side!=='back';if(backFace)this.drawPancakeBack(c);else if(batter)this.drawBatterSurface(c,phase);else{c.filter=phase==='burnt'?'brightness(.48) saturate(.65)':'none';if(img.complete&&img.naturalWidth)c.drawImage(img,-185,-82,370,164);else this.ellipse(c,0,0,174,68,'#e6b766');c.filter='none'}if(this.step.side==='back'&&this.step.interaction==='COOK_TIMING')this.drawBackMarks(c,phase);if(this.step.interaction==='COOK_TIMING'&&this.step.side!=='back')this.drawCookSurface(c,phase);if(phase==='burnt')for(let i=0;i<8;i++){const xx=Math.sin(this.time*1.7+i*2)*110,yy=-74-((this.time*35+i*16)%100);this.ellipse(c,xx,yy,4,9,'#77716b55')}c.restore();if(bounce){c.save();c.globalAlpha=.13*bounce;c.strokeStyle='#fff8e7';c.lineWidth=8;c.beginPath();c.ellipse(640,415,197+18*(1-bounce),82+12*(1-bounce),0,0,Math.PI*2);c.stroke();c.restore()}}
  drawPancakeBack(c){const img=this.assets.ingredient;c.save();c.filter='brightness(.82) saturate(.88) sepia(.12)';if(img.complete&&img.naturalWidth)c.drawImage(img,-185,-82,370,164);else this.ellipse(c,0,0,174,68,'#d9984f');c.filter='none';c.beginPath();c.ellipse(0,0,178,76,0,0,Math.PI*2);c.clip();for(let i=0;i<18;i++){const a=i*2.399,r=.19+(i%5)*.145,x=Math.cos(a)*r*158,y=Math.sin(a)*r*57,rx=5+(i*7%10),ry=3+(i*11%6);c.globalAlpha=.20+(i%3)*.06;c.fillStyle=i%2?'#7c4428':'#fff0c1';c.beginPath();c.ellipse(x,y,rx,ry,a*.12,0,Math.PI*2);c.fill()}c.globalAlpha=1;c.restore()}
  drawBatterSurface(c,phase){const g=c.createRadialGradient(-36,-18,3,0,0,180);g.addColorStop(0,phase==='raw'?'#fff4dc':'#f4e5c4');g.addColorStop(.7,phase==='raw'?'#f2dfbb':'#e8ce9d');g.addColorStop(1,phase==='raw'?'#dfc191':'#c99456');this.ellipse(c,0,0,174,65,g);c.save();c.globalAlpha=.88;c.strokeStyle=phase==='raw'?'#fff9e9':phase==='edge'?'#bf8950':'#ad6538';c.lineWidth=phase==='raw'?7:phase==='edge'?9:11;c.beginPath();c.ellipse(0,0,172,64,0,0,Math.PI*2);c.stroke();c.restore();if(phase==='raw'){const gloss=c.createRadialGradient(-43,-23,1,-35,-20,66);gloss.addColorStop(0,'#fffdf2a8');gloss.addColorStop(1,'#fffdf200');this.ellipse(c,-35,-20,66,17,gloss)}}
  drawCookSurface(c,phase){if(['edge','bubbles','nearly','perfect','burnt'].includes(phase)){c.strokeStyle=phase==='burnt'?'#5b3527':phase==='perfect'?'#a95e2f':phase==='nearly'?'#b97941':'#c38748';c.lineWidth=phase==='perfect'?13:phase==='nearly'?11:8;c.beginPath();c.ellipse(0,0,169,62,0,0,Math.PI*2);c.stroke()}if(['bubbles','nearly','perfect','burnt'].includes(phase)){const count=phase==='bubbles'?7:11;for(let i=0;i<count;i++){const a=i*2.399+Math.floor(this.cookElapsed*1.4)*.13,r=24+(i%4)*30,bx=Math.cos(a)*r,by=Math.sin(a)*r*.35,pop=(this.time*1.8+i*1.7)%2.8,radius=pop<.55?2+pop*5:Math.max(0,6-(pop-.55)*6);if(radius){c.fillStyle=phase==='perfect'?'#a8613970':'#c4905b82';c.beginPath();c.arc(bx,by,radius,0,Math.PI*2);c.fill();c.strokeStyle='#fff0d1aa';c.lineWidth=1.5;c.stroke()}}}if(phase==='burnt'){c.fillStyle='#39241f77';c.beginPath();c.ellipse(0,0,159,54,0,0,Math.PI*2);c.fill()}}
  drawBackMarks(c,phase){c.save();c.strokeStyle=phase==='raw'?'#d8be92':phase==='burnt'?'#683d2b':'#a56437';c.lineWidth=6;for(let i=-2;i<=2;i++){c.beginPath();c.ellipse(i*42,-4,17,7,.12,0,Math.PI*2);c.stroke()}c.restore()}
  drawSyrupOnCake(c){const img=this.assets.ingredient;c.save();c.beginPath();c.ellipse(640,414,185,78,0,0,Math.PI*2);c.clip();if(img.complete&&img.naturalWidth)c.drawImage(img,455,332,370,164);for(const stroke of [...this.strokes,this.currentStroke||[]]){if(stroke.length<2)continue;c.lineCap='round';c.lineJoin='round';c.strokeStyle='#542b1d';c.globalAlpha=.48;c.lineWidth=this.step.strokeWidth+3;c.beginPath();c.moveTo(stroke[0].x,stroke[0].y);for(const p of stroke.slice(1))c.lineTo(p.x,p.y);c.stroke();c.globalAlpha=.91;c.strokeStyle='#a95724';c.lineWidth=this.step.strokeWidth;c.beginPath();c.moveTo(stroke[0].x,stroke[0].y);for(const p of stroke.slice(1))c.lineTo(p.x,p.y);c.stroke();c.globalAlpha=.36;c.strokeStyle='#ffd184';c.lineWidth=Math.max(2,this.step.strokeWidth*.22);c.beginPath();c.moveTo(stroke[0].x-this.step.strokeWidth*.15,stroke[0].y-this.step.strokeWidth*.15);for(const p of stroke.slice(1))c.lineTo(p.x-this.step.strokeWidth*.15,p.y-this.step.strokeWidth*.15);c.stroke();c.globalAlpha=1}c.restore()}
  drawAmountMeter(c){const phase=this.phase,left=466,width=348,target=phase.targetAmount,max=Math.max(target*1.25,phase.maxAmount),usable=width-8,current=Math.min(this.amount,max);c.fillStyle='#55443480';c.beginPath();c.roundRect(left,632,width,19,10);c.fill();c.fillStyle='#9ac59a';c.beginPath();c.roundRect(left+4+phase.minAmount/max*usable,635,Math.max(9,(phase.maxAmount-phase.minAmount)/max*usable),13,7);c.fill();c.fillStyle=this.overflow?'#df654e':'#d98b48';c.beginPath();c.roundRect(left+4,635,Math.max(7,current/max*(width-8)),13,7);c.fill();this.text(c,this.message||`${phase.label||'양'} ${Math.round(Math.min(1,this.amount/target)*100)}%`,640,676,16,this.overflow?'#ffd1c5':'#fff8e8')}
  drawCookMeter(c){const phase=this.cookPhase(),left=486,width=308,y=652;c.fillStyle='#55443478';c.beginPath();c.roundRect(left,y,width,13,7);c.fill();const a=(this.step.perfectStart-this.step.rawDuration)/(this.step.burnStart-this.step.rawDuration);c.fillStyle='#8fc58e';c.beginPath();c.roundRect(left+width*a,y+2,width*(1-a)-2,9,5);c.fill();const progress=Math.min(1,this.cookElapsed/this.step.burnStart);c.fillStyle='#f1a05d';c.beginPath();c.arc(left+progress*width,y+6.5,6,0,Math.PI*2);c.fill();const label={raw:'젖은 반죽',edge:'가장자리 익는 중',bubbles:'기포가 올라와요',nearly:'노릇하게 익어요',perfect:'뒤집기 좋은 순간',burnt:'타고 있어요'}[phase];this.text(c,label,640,683,14,phase==='burnt'?'#ffc9a9':'#fff9e9')}
  drawSyrup(c){this.drawSyrupOnCake(c);if(this.drawing){const p=this.lastPoint;this.ellipse(c,p.x,p.y,11,7,'#e8a755')}}
  easeOut(t){return 1-Math.pow(1-t,3)}easeInOut(t){return t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2}
  ellipse(c,x,y,rx,ry,color){c.fillStyle=color;c.beginPath();c.ellipse(x,y,rx,ry,0,0,Math.PI*2);c.fill()}
  text(c,value,x,y,size,color){c.save();c.font=`700 ${size}px sans-serif`;c.textAlign='center';c.textBaseline='middle';c.fillStyle=color;c.shadowColor='#38271e99';c.shadowBlur=3;c.fillText(value,x,y);c.restore()}
}
window.CookingInputAdapter=CookingInputAdapter;window.CookingInteractionSystem=CookingInteractionSystem;
